### ISSUE TITLE
Add unit tests for processing measurements

### ISSUE THREAD

**Issue by jfsiii** [RamonGebben/react-perf-tool#11]
There are unit tests for small utilities like formatting time but not the core features of the lib: processing and displaying React Perf values.
#9 is a result of a change in record format. #10 attempts to address the changes but, without tests, it's impossible to know if these are all the changes required, or if they have unintended consequences.

**Comment by RamonGebben** [comment]
Thanks for pointing this out I will try to address this problem as soon as possible.

**Comment by RamonGebben** [comment]
From [this blogpost](https://reactjs.org/blog/2017/09/26/react-v16.0.html#react-addons) you can learn that addons which drive this package are no longer supported.

You can read here [how to use the browsers profiler](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab) to accomplish the same results:


In response to that I'm deprecating this package.
