### ISSUE TITLE
Provide as a Chrome plugin?

### ISSUE THREAD

**Issue by bebraw** [RamonGebben/react-perf-tool#12]
I wonder if it would be possible to wrap this into a browser plugin. You could detect `Perf` (or `React.Perf`?) from the global and then hook into that. There's a browser plugin for Redux devtools so examining their wrapping could be worthwhile to see how to achieve this.

**Comment by RamonGebben** [comment]
That's a great idea, thanks.
Thinking about it now it would also solve 2 other issues I've being working on. I will look into making it a chrome extension first.

**Comment by Pines-Cheng** [comment]
can't agree it any more.

**Comment by RamonGebben** [comment]
From [this blogpost](https://reactjs.org/blog/2017/09/26/react-v16.0.html#react-addons) you can learn that addons which drive this package are no longer supported.

You can read here [how to use the browsers profiler](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab) to accomplish the same results:


In response to that I'm deprecating this package.
