### ISSUE TITLE
Unmet dependency for "react": "^15.2.1",     "react-dom": "^15.2.1",

### ISSUE THREAD

**Issue by echorohit** [RamonGebben/react-perf-tool#16]
Hi,
I am getting unmet dependency error while trying to install it on 
"react": "^15.2.1",
"react-dom": "^15.2.1",

Any plan to support these version?

**Comment by RamonGebben** [comment]
Sure I'll try to send an update when I can, thanks for pointing it out.

**Comment by echorohit** [comment]
Shall I do that and Raise a PR?

**Comment by RamonGebben** [comment]
That would be great!

**Comment by RamonGebben** [comment]
I've updated the version of the peer dependencies.
@echorohit Could you check if your problem still occurs on `0.2.1`?
