### ISSUE TITLE
Styles aren't being included

### ISSUE THREAD

**Issue by joeyfigaro** [RamonGebben/react-perf-tool#17]
Component doesn't seem to have any styles, but I see that you're importing a bunch of partials/sheets. Webpack config is set to handle `.css` with `style-loader` - do I need to do anything else?

**Comment by wesm87** [comment]
This doesn't seem to mentioned in the README but you need to import the styles manually, like so:
```
import 'react-perf-tool/lib/styles.css';
```

**Comment by RamonGebben** [comment]
I'll add it to the README for now and will find a better solution so this will not be required any more.

**Comment by RamonGebben** [comment]
I've added it to the README, however soon I'd like to move Style-Components so loading styles would not be needed anymore.
