### ISSUE TITLE
How do you view the graph?

### ISSUE THREAD

**Issue by elliotec** [RamonGebben/react-perf-tool#18]
There is nothing that says how to actually use it. Install works... now what

**Comment by RamonGebben** [comment]
Make sure you have the react performance testing utils installed and require/import like so: 

```javascript
import ReactPerfTool from 'react-perf-tool';
import Perf from 'react-addons-perf';
import 'react-perf-tool/lib/styles.css';
```
Then further in your app you can use it like so:

```javascript
export default function YourApp(props) {
  return (<div className="your-app">
    {/*...yourApp */}
    <ReactPerfTool perf={Perf} />
  </div>);
```

**Comment by elliotec** [comment]
That's all there. No errors. Where do I go to see the graph?

**Comment by RamonGebben** [comment]
The panel should be visible by default. Maybe try hitting one of the keyboard shirt cuts to enable it.`alt+shift+p`. If this does not work can you try to reproduce the issue in a [webpackbin](https://www.webpackbin.com) so I can have a look at what's going wrong.
