### ISSUE TITLE
Does not work with React 16

### ISSUE THREAD

**Issue by Kerumen** [RamonGebben/react-perf-tool#19]
I get the error:
```
./node_modules/react-addons-perf/index.js
Module not found: Can't resolve 'react-dom/lib/ReactPerf' in '/Users/yann/git/PayFit/hr-apps/node_modules/react-addons-perf'
```
This is because, as stated in the [docs](https://reactjs.org/docs/perf.html), `react-addons-perf` is not supported with React 16:
> Note:
As of React 16, react-addons-perf is not supported. Please use your browser’s profiling tools to get insight into which components re-render.

**Comment by RamonGebben** [comment]
I'll look into it. Thanks for reporting

**Comment by RamonGebben** [comment]
From [this blogpost](https://reactjs.org/blog/2017/09/26/react-v16.0.html#react-addons) you can learn that addons which drive this package are no longer supported.

In response to that I'm deprecating this package.
