### ISSUE TITLE
React Versions

### ISSUE THREAD

**Issue by chrisblossom** [RamonGebben/react-perf-tool#3]
Is this only for React v15 or can it be used with v0.14? If so, would you accept a PR to move React to the peer deps as follows:

``` js
...
  "peerDependencies": {
    "react": "^0.14.0 || ^15.0.0",
    "react-addons-perf": "^0.14.0 || ^15.0.0"
...
```

**Comment by RamonGebben** [comment]
@chrisblossom sure that would be acceptable. However I'm not familiar with the `||` operator in the version. Could you link some documentation on this subject?

As far as I know the measurements should still work for 0.14.x after the fix for #2.

**Comment by chrisblossom** [comment]
This is how [reactjs/react-redux/package.json](https://github.com/reactjs/react-redux/blob/master/package.json#L97) does it. https://docs.npmjs.com/misc/semver explains it in detail.

**Comment by RamonGebben** [comment]
Sure make it work. Do you want to send a pull request to close the issue. Or shall I pick it up?
