### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by gmaclennan** [RamonGebben/react-perf-tool#5]
This looks great, but the `README` unfortunately does not tell you how to use it. I added the code as explained in the `README` but I see nothing. From reading through the source it looks like pressing `alt+shift+p` should do something. Tried that (on a mac) and nothing. Any pointers? Would be great to update the `README`

**Comment by RamonGebben** [comment]
That's weird and unexpected to happen.
If you include it in the root of your application it should show up once the app is initialised.

Could you show me how you are trying to use it?

**Comment by gmaclennan** [comment]
Ok, I figured out a problem with how it was being loaded. It would be good to add a line to the `README` that says something like "When included in the root of your application 'this button will show up' or 'this overlay will show'" or something like that, that helped me know that I was doing something wrong.

Another issue now:

```
Error: Cannot find module '!!./../../node_modules/css-loader/index.js!./container.css' from '/Users/gregor/Dev/DdDev/mapfilter-new/node_modules/react-perf-tool/lib'
```

Perhaps because I don't use webpack? Looks like the modules weren't transpiled correctly in the npm release?

**Comment by RamonGebben** [comment]
Thanks for discovering that. I will look into it. 
Could you show me the environment you are trying to run in?

**Comment by RamonGebben** [comment]
Since there is no response on this issue anymore I'm closing it for now

**Comment by danieleleoni** [comment]
Same for me. I did not understand how it works.
