### ISSUE TITLE
Does not work with isomorphic applications

### ISSUE THREAD

**Issue by azz0r** [RamonGebben/react-perf-tool#6]
ReferenceError: document is not defined

**Comment by RamonGebben** [comment]
For the moment I'm not planning to support isomorphic rendering. 

Because it's not very familiar to me. You are welcome to look into it and tell me what would need to change in order to support it. Otherwise I will close this issue and make a note of it in the back log.

**Comment by RamonGebben** [comment]
Since there was no response by @azz0r I will close this issue and consider it as a feature for the future

**Comment by tconroy** [comment]
would just like to add +1 for requesting universal rendering support. An easy hack is to check for window or document being defined before setting up the component, this way you can defer any processing until the client bundle hooks in and that check becomes truthy.
