### ISSUE TITLE
Measurement parsing fails

### ISSUE THREAD

**Issue by borisyankov** [RamonGebben/react-perf-tool#9]
After measurement stop I get an error:

```
react-perf-tool.js:4351 Uncaught TypeError: Cannot read property 'split' of undefined
```

On this line:

```
var label = measurement['Owner > component'].split(' > ').pop();
```

**Comment by RamonGebben** [comment]
@borisyankov Can you give me some more context on how to reproduce this?
For instance how are you using it in your project?

**Comment by jfsiii** [comment]
I'm seeing this as well. I'm using as shown in the README. I'm using React `15.1.0`

It appears the data structure doesn't match what's expected, I'll submit a PR.

**Comment by theoutlander** [comment]
Shouldn't a similar fix be applied in TimeWasted.js?

**Comment by RamonGebben** [comment]
Yes but because there was a related issue already posted it will be fixed in a patch for that issue.
